In [1]:
import numpy as np


In [2]:
np.__version__

'1.21.5'

In [4]:
data=np.random.randn(5,3)    #it works randomly. creates a random matrix of 3 rows and 2 columns
data

array([[-0.54034187, -0.05075864, -0.12900355],
       [ 1.22058007,  0.82485796,  0.26251009],
       [ 0.43886503, -0.14286795,  0.84994874],
       [-0.97296218,  0.71002099,  1.15434641],
       [-1.50401394,  1.55810021, -0.17116144]])

In [5]:
data.shape                 #the data shows the size

(5, 3)

In [6]:
data.dtype                 #shows the data type

dtype('float64')

In [10]:
liste=[[3,17.3,25,96.5,8],[18,55,45.8,17,10]]
np_array=np.array(liste)                             #returns the list to the array type
np_array

array([[ 3. , 17.3, 25. , 96.5,  8. ],
       [18. , 55. , 45.8, 17. , 10. ]])

In [11]:
dizi=np.zeros(5)           #Fill the array with zero
print(dizi)

[0. 0. 0. 0. 0.]


In [13]:
dizi=np.ones((4,7))        #Fill the array with one
print(dizi)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [14]:
dizi=np.ones((2,4,5))
print(dizi)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [15]:
dizi=np.array([1,2,3],dtype=int)

print(dizi)
dizi.dtype

[1 2 3]


dtype('int32')

In [18]:
dizi=dizi.astype(np.float64)
print(dizi)
print(dizi.dtype)

[1. 2. 3.]
float64
